# Generated by Django 4.0.6 on 2022-07-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('bill_to', models.CharField(blank=True, default='', max_length=100)),
                ('bill_from', models.CharField(blank=True, default='', max_length=100)),
                ('line_item', models.CharField(blank=True, default='', max_length=100)),
                ('monetary_value', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
