# Generated by Django 4.0.6 on 2022-07-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='owner',
        ),
    ]
