# Generated by Django 4.0.6 on 2022-07-29 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0003_remove_invoice_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
