# Generated by Django 4.1 on 2022-08-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='monetary_value',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
