# Generated by Django 4.1 on 2022-08-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_monetary_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='monetary_value',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
